### ISSUE TITLE
Fetching data from the server again when scrolling up is glitch-inducing

### ISSUE THREAD

**Issue by gsklee** [jankuca/ng-scroller#3]
Check out this video:

https://vimeo.com/72580467

Simply put, users will feel weird when they discover they gotta wait for the content **they just scrolled pass through** to load again, and as can be seen inside the video, it can cause a very noticeable disruption to the browsing experience.

Why not simply use the cached removed content inside the memory?

The video also shows the white space issue reported in #2.

**Comment by jankuca** [comment]
Caching is not a part of the scroller. The data store object (app-specific) needs to handle this in a way appropriate for the given application.

I can improve the demo data store so that it invalidates data correctly but it does not change the fact that in an actual app, the developer will need to implement this themselves.

**Comment by gsklee** [comment]
As long as this part can be decided in the developer's discretion I'd say it's fine.
